# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b56393464e4dd389b7216e5d16ff4fba9a98bfee18b2686b688ba60da288afd58af80a0c9e5ff3d4c67225f96d5132d54304d90b53ae39a46de2a4ed9e0c63

test:
  secret_key_base: 545be23cff4347431395c95a05192ec782fc0d697b154888387e5027b916f32c6b1a3468b70a294f2d06107333bc87f45934825465cf694d49f56852abd010c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
